inherits: ..\\products_java.yml

dimensions:  
- alias:  operation
  values: [format_java] 

- alias:  fileformat
  values: [pdf, docx, png, jpeg] 

outputPath: "comparison\\{product}\\{fileformat}.{lang}.md"
