inherits: ..\\products_net.yml

dimensions:  
- alias:  operation
  values: [format_net] 

- alias:  fileformat
  values: [pdf, docx, png, jpeg] 

outputPath: "comparison\\{product}\\{fileformat}.{lang}.md"