inherits: ..\\products_nodejs.yml

dimensions:  
- alias:  operation
  values: [format_nodejs] 

- alias:  fileformat
  values: [pdf, docx, xlsx, pptx, png, jpeg, jpg] 

outputPath: "comparison\\{product}\\{fileformat}.{lang}.md"
